### ISSUE TITLE
Create an endpoint for auto-invitation

### ISSUE THREAD

**Issue by moshfeu** [Coding-Coach/slack-bot#4]
Currently, there is a link in our websites and online profiles to join our Slack organization.
Unfortunately, the link is expires every 3 months so we should replace it everywhere.

We want to implement the auto-invitation process so the user will fill their email address and they will received an invitation.

The task here is to add a route for receiving invitation request, and use Slack API to send the invitation.
Each client will implement the UI by itself.

**Technical notes:**

- The implementation can be inspired by https://github.com/outsideris/slack-invite-automation/blob/master/routes/index.js#L17
- Slack app is basically wraps an express server which can be access through `receiver.app` this way:

```js
app.receiver.app.get('/blabla', (req, res) => {
  // do your magic
});
```

Please create a Slack organization for testing. Once it's working for you, we'll merge it.

**Comment by arku** [comment]
@moshfeu I would like to take a stab at this.

**Comment by moshfeu** [comment]
All yours @arku thanks!

**Comment by moshfeu** [comment]
I didn't notice that `app.receiver` is a `private` member.
Although, it's possible to use it because we're not using TypeScript, we can check for a more right way.
A direction could be [customized receiver](https://slack.dev/bolt/concepts#receiver).
I also asked the bot repository guys, maybe there is even a better way.

https://github.com/slackapi/bolt/issues/434

**Comment by moshfeu** [comment]
Seems like there is a way for the bot to use an existing express instance.

https://github.com/slackapi/bolt/issues/434#issuecomment-602968040
